### PR TITLE
Asyncio support

### PR DESCRIPTION
**Pull request by vxgmichel**
Hi Tiago,

I've been working on the asyncio support for PyTango lately, so you might want to have a look. It seems to work fine from both client and server sides, there is an example [here](https://github.com/vxgmichel/pytango-asyncio-examples) if you want to give it a try. I tried not to change your code as much as possible, except for green.py that I had to refactor.

For the server, I simply had to add a new asyncio executor with an interface similar to your gevent executor. For the client, I tweaked it a bit so that each green mode (Synchronous, Gevent, Futures and Asyncio) have its own executor, submitter and waiter. The waiter is just a function to get the actual result out of the asynchronous result.

I haven't tested the other modes (Futures and Gevent) so I'm not 100% sure I didn't break them. In any case, it shouldn't be more than typos.

I'm really satisfied and excited about the results, it works just as I expected.
Let me know what you think of it,

Thanks,

Vincent

### CODE REVIEW

**Comment by tiagocoutinho** [comment]
Thanks for the PR.
It really adds great functionality!
After the python asyncio API stabilizes we should talk about the possibility to integrate the tango event loop with the asyncio. It would be great if we could use the *await* expression, *asynch def*, *asynch with* and *asynch for* statements with tango

**Comment by tiagocoutinho** [comment]
Just realized I introduced a conflict in the master branch due to another bug fix.
Would you be able to resolve the conflict or do you want me to do it?

**Comment by vxgmichel** [comment]
By the way, I made a [PR to asyncio](https://github.com/python/asyncio/pull/273) in September. It adds the possibility to submit a coroutine from a thread to an asyncio event loop. It's been accepted and called [run_coroutine_threadsafe](https://docs.python.org/3/library/asyncio-task.html#asyncio.run_coroutine_threadsafe). This function will definitely simplify the implementation of the asyncio worker.

>  It would be great if we could use the await expression, asynch def, asynch with and asynch for statements with tango 

Also, I already have an [example of device](https://github.com/vxgmichel/pytango-asyncio-examples/blob/master/server35.py) that uses `async` and `await` ;-)

> Just realized I introduced a conflict in the master branch due to another bug fix.
Would you be able to resolve the conflict or do you want me to do it?

I can have a look at this conflict, what is it about exactly?

**Comment by vxgmichel** [comment]
I think I fixed it but please don't merge it yet, it's untested.

**Comment by tiagocoutinho** [comment]
So you were the one who added [run_coroutine_threadsafe](https://docs.python.org/3/library/asyncio-task.html#asyncio.run_coroutine_threadsafe)! 
Nicely done :+1:  ! My hat's off to you. Look forward for your ok to merge the pull request
I the mean time I will tag v8.1.8 since people are asking for it
You PR will deserve a special 8.1.9 :-)

**Comment by vxgmichel** [comment]
Thanks! :-)

I just wrote unit tests for asynchronous servers. It also run tests for the gevent  green mode, so you might want to have a look (see the [Test section in the readme](https://github.com/vxgmichel/pytango-asyncio-examples)). Anyway, the tests pass so I guess I didn't break too much code. Let me know if you have other tests I can run.

Also, this `get_event_loop` feature you recently added for event submission on the client side seems really similar to the `async_worker` on the server side. Do you think it would be possible to merge them together? Maybe the workers could move out of `server.py` to go to `tango_gevent.py` and `tango_asyncio.py`?

In any case, I think it would be good to have someone review my refactoring of `green.py`, and maybe settle on a standard interface (executor, submitter, waiter, etc.) for the different green modes.

 Thanks for the 8.1.8 release by the way ;-)

**Comment by johanfforsberg** [comment]
I've been playing with the asyncio stuff in this branch for a while and haven't found any issues so far. I've also read through the PR and it looks fine to me. My only concern is whether it might break some of the gevent or futures behavior, neither of which I am using much.

My vote is for merging, this PR has been lying around for way too long.

**Pull request merged**
