### PR TITLE
Release v9.2.0 

### PR DESCRIPTION
**Pull request by vxgmichel**
Are we ready for the release?

### CODE REVIEW

**Comment by tiagocoutinho** [comment]
Hi @vxgmichel, I think `9.2.0final0` should be only after features #7, #9, #11, #13 are implemented.
I propose to name it `9.2.0b3` since the full 9.2 API is still not finished.

**Comment by tiagocoutinho** [comment]
Ok then, after discussion in gitter it is decided that we should name this one `9.2.0`

**Comment by tiagocoutinho** [comment]
Ok, if there are no objections I can merge the PR

**Comment by vxgmichel** [comment]
Great, I'll do the release once it's merged!

**Pull request merged**
